import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: '잽싸게',
  description: '인천 지하철 실시간 좌석 매칭',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body className="antialiased">{children}</body>
    </html>
  )
}

/*
 * ========== 기존 layout.tsx (보존) ==========
 *
 * import type { Metadata } from "next";
 * import localFont from "next/font/local";
 * import "./globals.css";
 *
 * const geistSans = localFont({ src: "./fonts/GeistVF.woff", variable: "--font-geist-sans", ... });
 * const geistMono = localFont({ src: "./fonts/GeistMonoVF.woff", variable: "--font-geist-mono", ... });
 *
 * export const metadata: Metadata = {
 *   title: "Create Next App",
 *   description: "Generated by create next app",
 * };
 *
 * export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
 *   return (
 *     <html lang="en">
 *       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
 *         {children}
 *       </body>
 *     </html>
 *   );
 * }
 */
